# Generated by Django 5.0.6 on 2024-05-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news_dislikes_news_likes_alter_news_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(upload_to='images', verbose_name='Картинка'),
        ),
    ]
